### ISSUE TITLE
RS School (Abulkosim)

### ISSUE THREAD

**Issue by Abulkosim** [Jh33z/online-zoo#1]
Hello! Sorry for disturbing you, but I couldn't find any other way to message you. I'm from RS School. You checked my work today (online-zoo), and you gave me 68/70, but my actual score is 1/70. I think you made a mistake. Could you please change that?
![image](https://user-images.githubusercontent.com/72679180/200181249-b64bcc03-2f39-4283-9140-a993448d9fa9.png)

**Comment by Jh33z** [comment]
Hello. I'm sorry my friend that was my fault, I just updated C-C review,
you can check it.
Good luck!

**Comment by Abulkosim** [comment]
Thank you 😊
